github:
  homepage: https://datasketches.apache.org
  ghp_branch: gh-pages
  ghp_path: /docs

  protected_branches:
    master:
      required_pull_request_reviews:
        dismiss_stale_reviews: false
        required_approving_review_count: 1
      required_signatures: false
      required_conversation_resolution: false
